# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e00c7c32221f7852f31a0677f7366be1801ab9219ae8973a03997281fe65d7a4f713838e5d7891b97530e437ca56f6816cda510775e85c6d6f63ce1f76b0ca2

test:
  secret_key_base: 210f43ac80a9fa39b95de7086dba9ddae1535c299c30eb86d4e2cca597eb40a68a4eb57564c44cbb2dbe6ded5676145324de7d63d1b03b10142821aaa1f45073

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
